# Generated by Django 6.0 on 2025-12-09 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen', models.TextField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En_proceso', 'En proceso'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
