# Generated by Django 6.0 on 2025-12-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creat_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
